### ISSUE TITLE
failed to generate dataset

### ISSUE THREAD

**Issue by maximilianchen** [tuan3w/cnn_vocoder#4]
Hi, I'm recently building the mcnn vocoder based on your code. However, when I tried to generate training dataset via the command line python preprocess.py along with the necessary parameters, it returned  0it [00:00, ?it/s] on the terminal, without any dataset generated. I wondered there could be any solution to this problem. Thanks a lot.

**Comment by tuan3w** [comment]
Hi @maximilianchen,
What parameters did you use for preprocessing data ? `path/to/ljspeech/dataset` is just placeholder. You should change it to right path to ljspeech dataset.

**Comment by maximilianchen** [comment]
> Hi @maximilianchen,
> What parameters did you use for preprocessing data ? `path/to/ljspeech/dataset` is just placeholder. You should change it to right path to ljspeech dataset.

Hi, @tuan3w, the following is the command line I typed in:

python preprocess.py \
> --out_dir ./dataset \
> --data_dir ./LJSpeech-1.1/wavs \
> --samples_per_audio 400 \
> --num_workers 4

**Comment by tuan3w** [comment]
It should be `./LJSpeech-1.1` .

**Comment by maximilianchen** [comment]
> It should be `./LJSpeech-1.1` .

Thanks a lot, @tuan3w. Now it works.
