### ISSUE TITLE
Merging with KeithIto Tacotron

### ISSUE THREAD

**Issue by sujeendran** [tuan3w/cnn_vocoder#5]
Hi! Can you tell me how I can use this vocoder with the KeithIto Tacotron 1 implementation? I read the description you told about making a network to change mel spectrogram to spectrogram. Is there any way to use the mel spectrogram directly to train this model? 
If so, will the quality of audio be considerably bad?

**Comment by tuan3w** [comment]
```js
mel_matrix = spectrogram dot mel-basis.
```
https://github.com/NVIDIA/tacotron2/blob/master/layers.py#L78
So  you can recover spectrogram from mel-spectrogram by solving least square problem. The solution is not perfect. You can learn a spectrogram enhancement network to improve the result.

**Comment by sujeendran** [comment]
Thanks for the response!
But I was wondering how to train your model on mel-spectrograms instead of spectrograms?
Do you mean the only way this is possible is again by just retaining the spectrogram and not by directly training using mel-spectrograms?

**Comment by tuan3w** [comment]
I tested with mel-spectrogram before, but it doesn't give good results.
