### ISSUE TITLE
stft() got an unexpected keyword argument 'fft_size'

### ISSUE THREAD

**Issue by maximilianchen** [tuan3w/cnn_vocoder#6]
Hi, @tuan3w . I'm training the vocoder, and it returns the following error:

/anaconda3/lib/python3.7/site-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1961: UserWarning: Default upsampling behavior when mode=linear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "train.py", line 152, in <module>
    train(args)
  File "train.py", line 100, in train
    post_loss, l1, l2, l3 = compute_loss(predict, wav)
  File "/Users/mac/Desktop/cnn_vocoder/loss.py", line 43, in compute_loss
    stft_pred, _, _= compute_stft(pred, n_fft=2048, win_length=1024, hop_length=256)
  File "/Users/mac/Desktop/cnn_vocoder/loss.py", line 29, in compute_stft
    stft = torch.stft(audio, win_length, hop_length, fft_size=n_fft, window=win)
TypeError: stft() got an unexpected keyword argument 'fft_size'

I wondered how this could be fixed.

**Comment by tuan3w** [comment]
Please check [requirements](https://github.com/tuan3w/cnn_vocoder/blob/master/requirements.txt#L1) . You might use a torch version newer than `0.4.0` .

**Comment by maximilianchen** [comment]
> Please check [requirements](https://github.com/tuan3w/cnn_vocoder/blob/master/requirements.txt#L1) . You might use a torch version newer than `0.4.0` .

Thanks @tuan3w. It was due to the Pytorch version.
