### ISSUE TITLE
requirements? (os, python)

### ISSUE THREAD

**Issue by marshonhuckleberry** [tuan3w/cnn_vocoder#8]

**Comment by tuan3w** [comment]
Hi @marshonhuckleberry ,
I used python3 and [pytorch 0.4.0](https://github.com/tuan3w/cnn_vocoder/blob/master/requirements.txt#L1)

**Comment by marshonhuckleberry** [comment]
> Hi @marshonhuckleberry ,
> I used python3 and [pytorch 0.4.0](https://github.com/tuan3w/cnn_vocoder/blob/master/requirements.txt#L1)

linux,win? wich python 3?

**Comment by tuan3w** [comment]
Hi @marshonhuckleberry,
It should work with any python 3.x version.
I only tested this code in Linux.

**Comment by marshonhuckleberry** [comment]
windows 10 64
python 3.7.7
